### ISSUE TITLE
Add Provider -> Custom Endpoint -> TypeError

### ISSUE THREAD

**Issue by mtmcduffie** [sync-for-science/procure-wip#14] opened 2020-08-13 18:05 UTC
Could very well be in my setup. 

1. I got the app up and running with npm run start. (Ubuntu 20.04 Docker image with npm installed)
2. Navigate to localhost:3000
3. Click to add a provider.
3. Select 'Custom Endpoint'
4. ![Screen Shot 2020-08-13 at 2 02 38 PM](https://user-images.githubusercontent.com/1562086/90170242-bc630080-dd6d-11ea-8c9b-b71791169496.png)
5. After saving.

TypeError: Cannot read property 'retryLimit' of undefined

![Screen Shot 2020-08-13 at 1 57 20 PM](https://user-images.githubusercontent.com/1562086/90170333-e74d5480-dd6d-11ea-973a-0ebd74ff3c06.png)

**Comment by gotdan** [comment] 2020-08-13 19:50
Thanks @mtmcduffie ! I'm able to reproduce - looks like an issue with endpoints that don't have a default query profile, displaying but not saving "Argonaut" as the value. You can work around this by selecting a different query profile and then fliping it back to Argonaut, but I'll push a quick change that should fix the issue.

**Comment by gotdan** [comment] 2020-08-13 19:55
Fixed via f278c8d - please reopen if still a problem.

**Closed by gotdan** 2020-08-13 19:55 UTC
